### PR TITLE
Fix include warnings

### PR DESCRIPTION
**Pull request by cboulay**
I ran into these include warnings again as in #24 . I guess the fix was never merged in.

This pull request also has my fixes for Matlab figure errors in pull request #58

### CODE REVIEW

**Comment by chkothe** [comment]
These are good fixes, thanks! And sorry for us being so slow on pull requests these days (wish I was less busy!). I hope no one is using vintage C compilers that don't have const with these headers... probably not anymore these days.

One little nitpick: I would personally be really reluctant to change internal struct/class layout (i.e., member order), and rather change the order in the constructors' initializer lists as it breaks binary compatibility between object files (e.g., passing an LSL data structures between user .dll's), also if anyone did that on the internal code of liblsl the results would be catastropic, because order really matters in there.

**Comment by chkothe** [comment]
Oh, one more thing: the best thing to do with the supergui code is to replace what is now 'handle' (and was 'real' before) by '', i.e., remove the type constraint -- because otherwise it won't work with older MATLABs (e.g., 2014a and before I think).

**Comment by chkothe** [comment]
OK, need to correct myself on the last point. Turns out that figure handles are both 'real' and 'handle' in these older MATLAB versions, so current code not a problem.

**Comment by cboulay** [comment]
It took a little bit of doing, but I managed to get rid of the other commit in this pull request to keep a narrow scope. The Matlab fix still exists in PR #58 
I also changed the constructors' initializer lists instead of changing the internal layout.

**Pull request merged**
