### PR TITLE
Update supported_devices.rst

### PR DESCRIPTION
**Pull request by A-Mark-Mento**
Hi- hoping to have our equipment included in this list.  We offer LSL support in our native data collection software as well as all versions of our SDK.

### CODE REVIEW

**Comment by cboulay** [comment]
Hi, glad to add your products.

However, we don't want to encourage a separate entry for every single device that supports LSL, especially when a cluster of those devices are supported via a single interface. To give you an extreme example, the OpenVR app supports several dozens of VR HMDs and motion controllers; we don't want 30+ lines for those, all linking to the same app.

Can you please change this PR to a single entry -- listing the different product names in that line -- linking to information about how to use those products with LSL, not to the products themselves? After a brief skim of your website, I think the best link is https://www.bitbrain.com/neurotechnology-products/software/programming-tools

**Comment by A-Mark-Mento** [comment]
Hi Chadwick - sure that makes sense.  Let me rework it a bit.

**Comment by A-Mark-Mento** [comment]
Ok updated.  Let me know if this one is ok.

**Comment by cboulay** [comment]
Terrific, thanks!

**Pull request merged**
