### PR TITLE
Fixed stream info header (C examples)

### PR DESCRIPTION
**Pull request by splendido**
As per the official [EEGMetaData specifications](https://code.google.com/p/xdf/wiki/EEGMetaData), single channel descriptors should appear under a `channels` node and the name for single channels should appear as a `label`node.

Recording with LabRecorder data generated with the current code results in a XDF file which is not correctly imported with `load_xdf` from the official MATLABImporter

### CODE REVIEW

**Comment by dmedine** [comment]
@splendido: Thanks for this work! Sorry for the long silence. I have been distracted with other projects and have not had time to test your changes -- or any other work on LSL. I perused them and they look excellent, though, so once I test it (just to be safe), I will merge this in.

**Comment by splendido** [comment]
Have you got any problems with the proposed changes?

**Comment by dmedine** [comment]
No. Of course not. I do apologize for not attending to this sooner -- I 
know it has been quite some time. I meant to test this and merge your 
fix in a long time ago, but it fell through the cracks. Thank you for 
being patient with me, LSL is a huge project and I have many other tasks 
-- some of which are very time critical and spring up out of no where. 
Again, I apologizing for not being more organized about your pull 
requests, I appreciate your contributions very much. This was merely an 
oversight on my part.
-David

**Comment by dmedine** [comment]
Actually what me be the issue here is that I recently cleaned out a 
bunch of bloat from the .git directory. It seems to have wiped out all 
the pending pull requests. Can you make your request again please?
Thanks,
David

**Comment by dmedine** [comment]
Luca et al.,
In order to recover your PR, Christian is going to manually replace the 
existing lines of code with yours so that you don't need to re-submit. 
We will then re-nuke the repo (clean more bloat) and pull requests will 
perhaps be re-destroyed.

Thanks again for this and sorry for the mess.

**Comment by splendido** [comment]
Ok, fine, no worries, I'm sorry you had problems with the repository.

Thank you for your time and the clarification!

**Pull request closed without merging**
