### PR TITLE
Rename LSL_ROOT to LSL_INSTALL_ROOT

### PR DESCRIPTION
**Pull request by tstenner**
See discussion in #241

### CODE REVIEW

**Comment by dmedine** [comment]
I also have to _not_ disable the boost autolinking for this to work (https://github.com/sccn/labstreaminglayer/blob/master/cmake/LSLAppBoilerplate.cmake#L48)

**Comment by dmedine** [comment]
Finally, the generated project includes a non-existent file called mocs_compilations.cpp. Can you explain this? I can't locate where it comes from.

**Comment by dmedine** [comment]
I understand now about the mocs etc. This is all handled automajically by cmake's qt module and appears to by working quite well.

**Comment by tstenner** [comment]
> I am still confused as to the use of /cmake in the append. This prevents my build from working, on Windows anyway.
Fixed in 127b082 (thanks to Chadwick for the suggestion).

> I also have to not disable the boost autolinking for this to work
This shouldn't be needed if CMake finds Boost, but I also don't remember why this is needed after all. Removing it /discussing the removal should be in a separate PR.

**Comment by dmedine** [comment]
Ok. I am going to pull this in and start a new pr to deliberate the autolink issue.

**Pull request merged**
