### PR TITLE
Fixed bug in C API that would cause functions lsl_pull_chunk_* to fail.

### PR DESCRIPTION
**Pull request by serafperd**
You are welcome :)

### CODE REVIEW

**Comment by cboulay** [comment]
I'm not sure that's correct. If you look 2 lines above, `data_buffer_elements % num_chans != 0` is being checked to make sure that `data_buffer_elements` is an even multiple of the number of channels. This tells me that `data_buffer_elements` should be equal to number_of_samples * number_of_channels.

In your change, you're comparing `data_buffer_elements != timestamp_buffer_elements`, but `timestamp_buffer_elements` should only have 1 element per sample, regardless of how many channels there are. So this comparison will fail whenever there is more than 1 channel.

**Comment by dmedine** [comment]
I have never seen lsl_pull_chunk_ fail before. Can you please provide some information about circumstances that have caused this for you? Thanks.

**Comment by cboulay** [comment]
I think one change that could be made to that line that would help with readability, and maybe even fix a problem if there's a compiler doing some weird order of operations, is the following:

`if (timestamp_buffer && max_samples != timestamp_buffer_elements)`
becomes
`if (timestamp_buffer && (max_samples != timestamp_buffer_elements))`

Maybe try that first?

**Comment by dmedine** [comment]
I doubt that this change would have an affect any compiler. It 
definitely helps with readability, though. I definitely thought it was 
the other way when I glanced at it before. For now, I'm inclined to 
leave it as is until more info comes in. I'm super curious about the bug 
that initially caught the op's attention.

**Comment by mgrivich** [comment]
The compiler will certainly get the order of operations correct. A human 
on the other hand ...

**Comment by serafperd** [comment]
Hi everyone,
sorry for only joining the discussion that late, it has just come into my attention. Following your discussion and repeating my tests, it seems indeed that there is no bug. Here is what happened:

I have been testing the C API of liblsl, slightly modifying the labstreaminglayer/LSL/liblsl/examples/C/ReceiveDataC/ReceiveDataC.c and labstreaminglayer/LSL/liblsl/examples/C/SendDataC/SendDataC.c . Besides minor modifications (stream name, etc), I replaced the lsl_pull_sample_f with lsl_pull_chunk_f (changing of course also the necessary arguments in the inlet creation, etc). My example was crashing for no apparent reason. The equivalent Python example was working fine. Further debugging led me to the file and line in question, which is C-API specific, so it made sense that it could be a bug. Changing the line (further misled by the phrasing in the error thrown) as I had suggested, fixed my example. 

My understanding after reading the documentation of lsl_pull_chunk_f was that the data_buffer_elements and timestamp_buffer_elements should be the same number. Since I had 8 channels in my example and I wanted chunks of 10 samples, I used (...80,80,...) as arguments. This line was of course crashing, since it is clear to me now that data_buffer_elements should be samples*channels (ChunkSizeInSamples * channels, 8*10=80 in my case), while timestamp_buffer_elements should be equal to samples (ChunkSizeInSamples, 10 in my case). After fixing this line to my proposition, my problem was solved, thus I considered there is a bug. The error line thrown corroborated my false idea.

Bottom line, there is no bug, but imho it is worth to: 
a) Improve the input/output explanations in comments preceding the definition of lsl_pull_chunk* functions. 
b) Improve the error message's clarity in function pull_chunk_multiplexed.
c) Maybe replace the existing examples (or add new ones) with ones using pull_chunk (it is very unlikely that biosignals will be acquired sample-by-sample and biosignal acquisition is still the most popular reason why someone will use lsl). Looking at the arguments in such an example would make everything clear to begin with.

There was another colleague, long-term user of the Pyhton version of LSL, that was debugging that with me and he fell into the same trap for more than an hour, so, I do not think that it is (only) that I am stupid :).

Thank you for the time!

**Pull request closed without merging**
