### PR TITLE
pylsl define argtypes for some of the XMLElement functions. This allo…

### PR DESCRIPTION
**Pull request by cboulay**
…ws pylsl in OS X to work. Also tested with Windows 10 + python 2.7 x64. Please test in your system before merging. @dmedine said he had some errors with this in his Windows system but I don't see how the error he reported could come from these changes. If the errors were from these changes then they would have to be something not present in Windows 10 Python 2.7 x64.

### CODE REVIEW

**Comment by dmedine** [comment]
Thanks for this as well...

**Comment by chkothe** [comment]
In fact, seeing that omitting the argtypes and leaving it to the ctypes
package to figure them out can cause subtle issues e.g. on 64-bit builds, I
I think we should declare them for every lsl function used in pylsl.

Christian

**Comment by cboulay** [comment]
I was a little bit worried about doing that because my [previous pylsl changes](https://github.com/sccn/labstreaminglayer/blob/master/Apps/LabRecorder/src/pylsl/pylsl-mac-exp.py#L1004-L1183) that did that also seemed to cause problems in Windows. Mind you, I made some other changes that could have been the culprit, but I'm not sure. For now I thought it best to keep the changes minimal and deal with other problems as they crop up.

If you do want to make more argtypes definitions then maybe it's a good idea to start with only the remaining XMLElement functions and see if those cause problems before moving on to the outlet and inlet functions.

**Comment by chkothe** [comment]
Yes, seeing your point. Though I think the errors that David saw must have
been spurious since they related to something you didn't even touch if I
remember correctly (also these were compile errors, which are better than
runtime crashes). As long as we get the types exactly right,
stability/trustworthiness of the code should improve.

**Pull request merged**
