### PR TITLE
Wearable sensing

### PR DESCRIPTION
**Pull request by aojeda**

### CODE REVIEW

**Comment by aojeda** [comment]
Use this program to stream real-time data acquired by a [Wearable Sensing](http://www.wearablesensing.com) DSI headset to the local area network (LAN) via the [LSL](https://github.com/sccn/labstreaminglayer) library. Below we list the build instructions (including Bluetooth troubleshooting steps) for GNU/Linux, Windows, and Mac. All commands need to be typed on a terminal.

For deployment just copy the subfolder inside Deploy/ that correspond to your OS.

Note: You only need to re-build the app if for some reason the binary in the Deploy folder doesn't run on your system.

#Build#

##GNU/Linux##

1. Move to the dsi2lsl/ folder. Substitute "/.." by the specific full path to the dsi2lsl folder in your file system.

```bash
cd /../dsi2lsl
```

2. Compile the project,

```bash
gcc -DDSI_PLATFORM=-Linux-x86_64  -o "Deploy/Linux/dsi2lsl" dsi2lsl.c  DSI_API_Loader.c -ldl  -L /../dsi2lsl/Deploy/Linux -llsl
```

3. Configure Bluetooth. Pair the DSI device using the Bluetooth device manager. If you don't have the Bluetooth stack properly installed do so using the following command,

```bash
sudo apt-get install bluez bluez-tools
```

4. Find the serial port that corresponds to the device. To accomplish this we need to find the device's address with hcitool,
  and then bind to it,

``` bash
hcitool scan
rfcomm bind /dev/rfcomm0 xx:xx:xx:xx:xx:xx 1
```

where xx:xx:xx:xx:xx:xx represents the output of hcitool (see [this](http://www.westernwillow.com/cms/blog/franco/creating-bluetooth-serial-port-ubuntu) example). We'll need this info later at run time.


##Mac##

1. Move to the dsi2lsl/ folder as before,

```bash
cd /../dsi2lsl
```

2. Compile,

```bash
gcc -DDSI_PLATFORM=-Darwin-x86_64  -o "Deploy/Mac/dsi2lsl" dsi2lsl.c  DSI_API_Loader.c -ldl  -L /../dsi2lsl/Deploy/Mac -llsl64
```

3. Add the DSI device through the Bluetooth manager, then find the port using the following command,

```bash
ls -l tty.*
```
      
for us this returned /dev/tty.DSI7-017-BluetoothSeria. We'll need this info later at run time.


##Windows##

1. Move to the dsi2lsl/ folder as before,

```bash
cd /../dsi2lsl
```

2. Compile the project. We used out of the box MinGW distribution of gcc as the compiler (see a tutorial [here](http://www.mingw.org/wiki/howto_install_the_mingw_gcc_compiler_suite)), although MS Visual C++ and others may work as well,

```bash
gcc -DDSI_PLATFORM=-Windows-x86_32 -o "Deploy/Windows/dsi2lsl.exe" dsi2lsl.c  DSI_API_Loader.c -ldl  -L /../dsi2lsl/Deploy/Windows -llsl32
```

3. Add the device using the Bluetooth manager, then find the port by right clicking on the device and clicking Properties/Hardware. For us the port was COM49. We'll need this info later at run time.


#Examples#

The app runs in the same way on the three platforms. Below we illustrate the different options that can be used. With the exception of the option --help, all the others should be given in --NAME=VALUE format. Use a terminal to run the examples.

Note:
      1. Linux users, since the app uses the serial port to exchange data with the device, your account may need to have superuser privileges (use sudo before any command).
      2. Linux and Mac users may need to add the path the the folder containing the binary and libraries to the system library path, if so use the following command
      
``` bash
export LD_LIBRARY_PATH=/.../dsi2lsl_deploy_folder:$LD_LIBRARY_PATH
```

### --port ###
Specify the serial port with the --port option. If not specified, the API will look for an environment variable called DSISerialPort. This example uses the serial port that the device is binded to on GNU/Linux, for other platforms see the previous secton.

``` bash
./dsi2lsl --port=/dev/rfcomm0
```

### --lsl-stream ###
Specify the name of the LSL outlet that will stream the data to the local network. If omitted, the default name WS-default will be used

``` bash
./dsi2lsl --port=/dev/rfcomm0 --lsl-stream-name=mystream
```

### --montage ###
Specify the montage, a list of channel specifications, comma-separated without spaces, (can also be space-delimited, but then you would need to enclose the option in quotes on the command-line). If omitted all available channels will be used.

``` bash
./dsi2lsl --port=/dev/rfcomm0 --lsl-stream-name=mystream --montage=F3,C3,P3,P4,C4,F4,Pz
```

### --reference ###
Specify the reference, the name of sensor (or linear combination of sensors, without spaces) to be used as reference. Defaults to a \"traditional\" averaged-ears or averaged-mastoids reference if available, or the factory reference (typically Pz) if these sensors are not available.

``` bash
./dsi2lsl --port=/dev/rfcomm0 --lsl-stream-name=mystream --montage=F3,C3,P3,P4,C4,F4,Pz --reference Pz
```

**Comment by dmedine** [comment]
Nice work, Alejandro! This looks awesome.

I'd like to request a couple of small changes before pulling. First, can you please remove the binaries from the PR? We try to avoid tracking any compiled objects. If there are 3rd party binaries, we'll need to upload them to the FTP and update the python scripts that fetch all the binaries from there. Please let me know and I'll take care of it.

Second, can you make a README file with exactly the text of your comment above in it and push that? Maybe you already did this and I missed it somehow.

Third can you remove lsl_c.h and lsl_cpp.h? I know this may require adjusting the include preprocessor directives and the build scripts/instructions, but everything should point to the files in the liblsl folder ("../../LSL/liblsl/include/lsl_c.h", etc.). I don't expect those files to change anytime soon, but just in case, I don't want to have multiple copies of anything in the repository. Thanks.

**Comment by aojeda** [comment]
Dead David, I have a new PR ready, before I submit it, please provide instructions on how to host Wearable Sensing libraries needed, e.g. ftp site, etc., they have communicated to me that hosting outside WS website is OK.
Thanks,
A

**Comment by dmedine** [comment]
Sorry for the delay. Holidays.

I was having trouble putting binaries up on the SCCN ftp before, but if 
you point me to them I will try again. There is a slot for LSL third 
party libs that can then be summoned by calling get_deps.py. However, I 
discovered at the LSL workshop in Delmenhorst a few weeks ago that some 
people are hesitant to call some weird-looking python script that 
downloads a bunch of stuff onto their computer. Such people prefer to 
get the libraries simply by downloading the pre-compiled binaries (which 
amounts to basically the same thing).

This brings up a larger issue about LSL which is the maintaining of 
releases.

Anyway, for the time being point me to your libs and I will try to take 
care of it. The edits to the python script are pretty minimal.

**Comment by tstenner** [comment]
> Hi, I'm currently using https://github.com/Neuroscale-Users/dsi2lsl to record data with Wearable Sensing. It seems to work well. Could this potentially be merged in soon? Thanks!

That repo has the issues outlined by @dmedine, #173 seems to be the cleaned up PR so I'll close this one.

**Pull request closed without merging**
