### PR TITLE
LabRecorder cmake

### PR DESCRIPTION
**Pull request by cboulay**
For #145 

This works in MacOS.
- Need homebrew qt5
- Need homebrew boost (1.62)

It also creates compilable solutions in Windows, but the product doesn't run due to a dynamic Qt error at runtime. 

I'll work on this again when I'm not so tired and busy.

### CODE REVIEW

**Comment by yyigeren** [comment]
Hi cboulay,

I have install qt5 and boost1.62 on my Mac.
I adjust the path of the qt and boost for the file qtbuild.sh

I got this error.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do you know what is the problem?
Thank you so much.

**Comment by cboulay** [comment]
I don't know what qtbuild.sh does. I assume it's for using qmake? I've never used that.

Are you using homebrew to install qt5 and boost?
You probably have to force link qt5. `brew link --force qt5`
Sorry I didn't provide more detailed instructions. The PR is not quite done. I'm just throwing up something that works for those that really need it.

**Comment by yyigeren** [comment]
Thanks for the quick reply.
I install it by homebrew. I will try your suggestion.

Can you share your compiled file in Mac?
Or your cmake code.

Thanks a lot.

Best,
Quanying

**Comment by cboulay** [comment]
In the LabRecorder directory...

```
mkdir build
cd build
cmake ..
make
```

That's it. No extra cmake options are needed if you used homebrew and force-linked as above.

**Comment by yyigeren** [comment]
Dear Chadwick,

Thanks for your reply.
I re-intalled everything by home-brew, and run brew link --force qt5

Then I used cmake .. And I got the following error.

CMake Error: The source directory "/Users/EGI/Downloads/LabRecorder" does not appear to contain CMakeLists.txt.


There is no CMakeLists.txt in the LabRecorder folder (I downloaded LabRecorder-1.12)


Can you please share your CMakeLists.txt with me?

Thanks a lot.


Best,

Quanying


--
Quanying Liu
PhD-Student
Neural Control of Movement Lab, ETH Zurich
Winterthurerstrasse 190
Building Y36 / Y17, Floor M, 8057 Zurich
http://www.ncm.hest.ethz.ch/

**Comment by cboulay** [comment]
You need all of my labstreaminglayer fork/branch, not just LabRecorder.
Here are some instructions from GitHub:
```
git clone --recursive https://github.com/sccn/labstreaminglayer.git
cd labstreaminglayer
git checkout -b cboulay-LabRecorder_cmake master
git pull https://github.com/cboulay/labstreaminglayer.git LabRecorder_cmake
```

**Comment by cboulay** [comment]
One more step I forgot: before you run cmake you'll have to download the binaries. The easiest (but slowest) way to do that is with a Python script provided by labstreaminglayer. In the labstreaminglayer, run `python get_deps.py` (or `python3 get_deps.py` if you're using python3.

**Comment by dmedine** [comment]
@cboulay I was going to try it on my office Mac at some point today, then merge. But,  I saw you say the PR is not quite done yet. Should I hold off?

**Comment by cboulay** [comment]
Please test.
But please hold off on merging. I at least have to write better instructions.

Also, I'd like to get it working in Windows. It's almost there, I just need to figure out why it's either not finding the Qt DLLs (which I have on the path) or there's a Qt conflict. It's probably a simple problem, I just haven't had time to go back to it.

Please test the Windows version too. The instructions are pretty much the same for Windows, but you may have to give the cmake command extra options:

`cmake .. -G <[generator](https://cmake.org/cmake/help/v3.1/manual/cmake-generators.7.html#ide-build-tool-generators)> -DCMAKE_PREFIX_PATH=<path_to_qt> -DBOOST_ROOT=<path_to_boost> -D BOOST_LIBRARYDIR=<path_to_boost_libs>`

The BOOST options are only needed if you don't have Boost 1.61 in C:\local (default). I should also add a MSVC default option for Qt.

**Comment by dmedine** [comment]
Ok. I'm not sure how much time I will have to test this. I wouldn't worry too much about getting it perfect on Windows, either (although that is desirable, obviously) since we have a vcproj for it.

**Comment by mgbleichner** [comment]
Hi Chad, 

just for reference. I followed your instructions and get the same error as yyigeren:

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see evocation)

 I am using OS X 10.11.6

**Comment by cboulay** [comment]
@mgbleichner , can you copy-paste a few more lines from the error? I don't know what library it's failing to find. My guess is either you didn't re-run `python3 get_deps.py` after getting my branch, or you didn't `brew link --force qt5`.

**Comment by mgbleichner** [comment]
@cboulay indeed I did not run `python get_deps.py` afterwards. 
It now works without problems. Thanks.

**Comment by cboulay** [comment]
I rebased, added some basic instructions, and tested a little more in Windows and Mac. This should be good to merge.

**Comment by tstenner** [comment]
On Ubuntu (and presumably Debian) zlib isn't found unless line 98 is replaced with `find_package(ZLIB)` (it uses the official <a href="https://cmake.org/cmake/help/latest/module/FindZLIB.html">FindZLIB.cmake</a>)

**Comment by cboulay** [comment]
@tstenner Thanks! ZLIB also works for Mac so it's an easy fix. I also took the opportunity to update the readme a little.

**Comment by tstenner** [comment]
The `cmake` folder with `FindLSL.cmake` could be useful for multiple apps, maybe it should be directly under the project root?
Currently it looks for both release and debug versions of the library and fails with a generic error message if one isn't found. From my point of view, requiring both to be preset is fine but the error message could be more helpful ("Couldn't find liblsl64-debug.so in /path/to/lsl/bin/").

Apart from that it works like a charm on Ubuntu 16.10, great work!

**Comment by cboulay** [comment]
Putting FindLSL.cmake into the Apps root is certainly something I want to do, especially because I have slightly different versions in the OpenVR, CereLink, and Emotiv apps. I just wanted my LSL-App cmake projects to mature a little before I made an upper-level (i.e. all Apps) cmake project. Your suggestion is a good step towards maturity.

**Comment by hannahlef** [comment]
Hi all. I have been trying to install LabRecorder but I couldn't make it work. I have installed homebrew, forced qt5, ran get_deps.py and when I enter cmake I get the following error:

CMake Error at CMakeLists.txt:11 (message):
  When building a single app out of tree you need to set LSL_ROOT ( cmake
  -DLSL_ROOT=/path/to/installed/lsl)
-- Configuring incomplete, errors occurred!

It may be a trivial question but where is LSL root supposed to be (in the liblsl folder?) and what should I do? I tried to run the following line:
cmake -DLSL_ROOT=/path/Apps/LabRecorder or cmake -DLSL_ROOT=/path/LSL/liblsl 
But it returns:
CMake Error: The source directory "path/Apps/LabRecorder/build" does not appear to contain CMakeLists.txt

I work on macOS sierra.

Thank you for your help!

**Comment by cboulay** [comment]
The instructions have changed a little bit. I'll make some changes to make this simpler then post here again.

**Comment by hannahlef** [comment]
Thanks a lot!

**Comment by cboulay** [comment]
It's going to be a little harder than I thought because I get_deps.py is not working for me right now so I can't replicate the default folder structure to tell cmake where to look for the LSL libs.

For now, for you, I'll instead just instruct you to build LSL and LabRecorder both. The instructions can be found [here](https://raw.githubusercontent.com/sccn/labstreaminglayer/master/INSTALL.md), but the short version:

Go into your root labstreaminglayer folder, then...
```
chmod +x ./fix_mac.sh
sudo ./fix_mac.sh
rm -Rf build
python3 lslbuild.py
```

**Comment by hannahlef** [comment]
I followed the instructions and I got some errors when running lslbuild.py.
...
CMake Error at /usr/local/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:15 (message):
  The imported target "Qt5::Core" references the file "/usr/local/.//mkspecs/macx-clang"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/local/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake"
  but not all the files it references.Call Stack (most recent call first):
  /usr/local/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake:50 (_qt5_Core_check_file_exists)
  /usr/local/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:167 (include)
  /usr/local/lib/cmake/Qt5Network/Qt5NetworkConfig.cmake:83 (find_package)
  /usr/local/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  Apps/LabRecorder/CMakeLists.txt:27 (find_package)
-- Configuring incomplete, errors occurred!
See also "/Users/joshuagold/Psychophysics/Projects/python_projects/labstreaminglayer-master/build/lsl_Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "lslbuild.py", line 183, in <module>
    builder.configure()
  File "lslbuild.py", line 110, in configure
    self.call_cmake(self.generator, self.cmake_conf, [self.sourcepath])  # generate CMake build files
  File "lslbuild.py", line 95, in call_cmake
    self.call(args)
  File "lslbuild.py", line 81, in call
    subprocess.check_call(args)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_INSTALL_PREFIX=/path/labstreaminglayer-master/build/lsl_Release/lslinstall', '-DCMAKE_BUILD_TYPE=Release', '-DLSL_USE_SYSTEM_BOOST=On', '/path/labstreaminglayer-master']' returned non-zero exit status 1

It also reported some warnings when running related to the boost version such as : "CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message): Imported targets not available for Boost version 106500".

I don't really know what I should do next...If I find a solution I'll let you know.

Thanks!!

**Comment by cboulay** [comment]
The Boost version warning is something really stupid about the way cmake handles boost; it only accepts versions of boost that it knows about and fails on anything newer. So if you're using cmake that's less than ~6 months younger than your boost version, it might not work. The easiest thing to do is to edit /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake near line 771 and just change the last ifelse condition from whatever version it accepts to 106501.

As for the Qt5, that one's unknown to me. I'd start by uninstalling reinstalling qt5 using homebrew. Be sure to `brew update` first.

**Comment by hannahlef** [comment]
It seems to work! I just added #include <iostream> at the top of socket_utils.h
Thanks for your help!

**Comment by cboulay** [comment]
I'm glad you're on your way.

It's not your problem (anymore), but it's still a concern to us that you needed to modify the core library at all. I'll make a new issue for it.

**Pull request merged**
