### PR TITLE
2nd attempt to plug outlet memory leak

### PR DESCRIPTION
**Pull request by dmedine**
Ok. I think I got it now. This seems not to crash anything, but more testing is required. I tested it sending 8 floats at a time at 100 Hz. I don't see any reason that this wouldn't scale up to any sampling rate or any data size (within the limits of LSL) but who knows. I would like to test it at high sampling rates, with large data sizes, and with markers.

### CODE REVIEW

**Comment by dmedine** [comment]
So, no. The memory profiler did show me a leak, and the above is a plug, but the underlying problem of high sampling rates is still unresolved. I think this has something to do with boost::asio. Either there is a bug in boost::asio itself that nobody till now has noticed (unlikely), or else a buffer is growing somewhere where I can't see it.

The heap memory management in LSL is fairly complicated and pointers get allocated and free in many different ways. I am going to leave the PR up for now but this is far from over.

**Comment by dmedine** [comment]
Ok. More updates. I am pretty much stuck. There are actually two leaks. The first is detectable with deleaker and perceptible through the usual Visual Studio diagnostic tools. This is the one I plugged here: https://github.com/sccn/labstreaminglayer/commit/38e4ced06c463f520196940ab1772ba2f7c56d33

However, with this patch, an outlet can only connect to one inlet. So it seems that this inner allocation of memory is not being freed. I tried using a shared_ptr here, but that doesn't work at all.

The other issue is that in addition to this, there is a slow leak that I cannot locate. I've been through the whole pipeline until samples go behind the shadow of boost::asio in the tcp service, and as far as I can tell, everything is rock solid. Boost is never wrong, so I doubt there is a problem there. Just in case, I pinged the boost list. I also tried adding some boost::asio::io_service::work objects as per this suggestion: https://stackoverflow.com/questions/32258890/c-boost-asio-async-send-to-memory-leak but it seems to have no effect.

**Comment by dmedine** [comment]
Also, did you guys mean to merge all that stuff into this branch? It has nothing to do with what I am working on here.

**Comment by cboulay** [comment]
I think your merge is backwards. Right now you are trying to merge master into mem_leak_2nd_attempt, but instead you should be attempting to merge mem_leak_2nd_attempt into master.

**Comment by dmedine** [comment]
That's odd. I am not actually attempting to merge anything at the 
moment. I just submitted a pr from a branch in the usual way...

**Comment by cboulay** [comment]
The new PR I made in #236 is going in the correct direction. Any new commits you make to the mem_leak_2nd_attempt branch will automatically show up there.

I copy-pasted your comments from here.

**Pull request closed without merging**
