### PR TITLE
Added simple tools to create debian packages

### PR DESCRIPTION
**Pull request by gisogrimm**
For easier integration on debian systems I wrote some very simple tools to create debian packages "liblsl" and "liblsl-dev".

To create the debian files, change to "Distribution" and type ./pack.sh

This does:

- build LSL/liblsl
- create liblsl package (from liblsl.so and LICENSE)
- create liblsl-dev (from lsl_c.h and lsl_cpp.h), which depends on liblsl

The version number is controlled by the file "version".

### CODE REVIEW

**Comment by chkothe** [comment]
Hi Giso, that's great stuff! We've been wanting to have Linux distribution packages for a long time... 
I wonder what the best place to put this would be in this directory structure, though. How about we put it under LSL/liblsl/distros/deb/? (just in case we want to add rpm at some point in the future)

I must say I understand about half of what you're doing in mkdeb... :) would you be willing to maintain this piece of LSL for the time being?

**Comment by gisogrimm** [comment]
Hi Christian, I was not sure about the best location - I can shift it to your suggestion. Also I was wondering if the version number is currently somewhere in the source tree, or is it part of your build and packaging system? Right now I guessed the version number.

I can maintain this. Actually the whole story is that we integrated basic LSL support in a virtual acoustic simulation tool developed mainly for audiological applications; since it is only Linux/debian it was the easiest to create these debian packages to track the external dependencies.

BTW, thanks a lot for LSL; it is a great tool, and I like the concept of connecting streams (until now we used OSC for data exchange in a very similar way).

**Comment by dmedine** [comment]
First of all, this is awesome. Thank you so much.

I concur with Christian that the we should put this in LSL/liblsl/distros/deb. We will also need to clean out a couple things (.gitignore and any .git, for example).

As far as the versioning is concerned, I've not been super responsible about this. We are currently at version 1.11 (although 1.12 is coming soon) but I'm not sure that is well reflected in the code anywhere. For package distribution purposes we should definitely be stricter about this, but as of this moment, I'm not quite sure what the best way to go about that is.

**Comment by dmedine** [comment]
First of all, this is awesome. Thank you so much.

I concur with Christian that the we should put this in LSL/liblsl/distros/deb. We will also need to clean out a couple things (.gitignore and any .git, for example).

As far as the versioning is concerned, I've not been super responsible about this. We are currently at version 1.11 (although 1.12 is coming soon) but I'm not sure that is well reflected in the code anywhere. For package distribution purposes we should definitely be stricter about this, but as of this moment, I'm not quite sure what the best way to go about that is.

**Comment by chkothe** [comment]
We have the version in the code actually, but you'd need to extract it from
there, maybe with some regex magic:
https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/src/common.h#L26

I hope this is workable (otherwise we could make a version.h).

Christian


First of all, this is awesome. Thank you so much.

I concur with Christian that the we should put this in
LSL/liblsl/distros/deb. We will also need to clean out a couple things
(.gitignore and any .git, for example).

As far as the versioning is concerned, I've not been super responsible
about this. We are currently at version 1.11 (although 1.12 is coming soon)
but I'm not sure that is well reflected in the code anywhere. For package
distribution purposes we should definitely be stricter about this, but as
of this moment, I'm not quite sure what the best way to go about that is.

—
Reply to this email directly or view it on GitHub
<https://github.com/sccn/labstreaminglayer/pull/87#issuecomment-184428202>.

**Comment by gisogrimm** [comment]
Ok, thanks for the comments. I will adopt your suggestions today; extracting the version number should not be an issue. The .gitignore contains only a single line with "*.deb" to ignore the generated package files.

On the long run it could also nice to package the LSL applications for debian, but I didn't manage to build/start them yet on linux (and it is lower priority for me right now).

Giso

**Comment by chkothe** [comment]
Yes, I would hold off on the applications for the time being. The library
is certainly the most important bit.

**Comment by gisogrimm** [comment]
Now this should work. To build debian packages, change to directory LSL/liblsl/distros/deb, and type ./pack.sh. Only the host platform is created, i.e., when multi-platform builds are required (e.g., 32/64 bit), call this on multiple build PCs.

If it is of interest I can check whether we can host a publicly available small unsigned repository for intel 32 and 64 bit builds (should be possible). An internal automatic build and packaging system is running anyway. Unfortunately I have no experience with official Ubuntu ppa and signing.

**Comment by dmedine** [comment]
Awesome. I will test and merge this in the next couple of days. I will 
also add .deb to the .gitignore file in the root directory.

**Comment by gisogrimm** [comment]
Actually I added .deb already in the top-level .gitignore in one of the
last commits.

Thanks a lot!

**Comment by dmedine** [comment]
Looks good, merging...

**Pull request merged**
