### PR TITLE
added -std=c++0x flag to cmake files

### PR DESCRIPTION
**Pull request by dmedine**
Non-ancient versions of Linux and OSX need this flag for gcc to build lsl. See closed issue #76 https://github.com/sccn/labstreaminglayer/issues/76

### CODE REVIEW

**Comment by chkothe** [comment]
We should really investigate why the heck that flag helped compile that one
boost issue, because with this option  will LSL no longer compile on many
older and embedded system.

**Comment by dmedine** [comment]
Interesting. I tested it on an old version of Linux (Ubuntu 10.10, 
32-bit) and it was fine. I didn't try it on older OSXs, since I don't 
have one handy.

Maybe this is the wrong thing to merge in. There is the CMAKE_SYSTEM 
variable which has information about which OS release is being used. 
Perhaps the thing to do is to check that and if it is above whatever 
value, add the flag.

**Comment by BorisMansencal** [comment]
Since issue #76 I have tried to compile with different version of gcc:
- With gcc 4.9.2 (on Fedora 21), current git version (without this patch) compiles ok
- With gcc  5.2.1 (on Ubuntu 15.10) or 5.3.1 (on Fedora 23), it does not compile (without the patch). 

The difference between gcc 4.9 and 5 is due to the ifndef on BOOST_NO_CX11_VARIADIC_TEMPLATES in external/lslboost/thread/pthread/once_atomic.hpp (l. 118). Both version do not compile the same code.
BOOST_NO_CX11_VARIADIC_TEMPLATES is defined in external/lslboost/config/compiler/gcc.hpp (l. 156). According to the test, gcc 4.9 defines  BOOST_NO_CX11_VARIADIC_TEMPLATES (when __GXX_EXPERIMENTAL_CXX0X__ is not defined, that is when -std=c++0x is not used). While, in any case, gcc 5 does not define  BOOST_NO_CX11_VARIADIC_TEMPLATES.
It seems that gcc 5 needs -std=c++0x to compile the first version of the code in once_atomic.hpp.

I can submit another patch that instead of setting -std=c++0x for all compilers under unix, check if we are using gcc with a version greater than 5 (whatever the OS is).
Basically, the patch would add for the target t, the following code in the CMakeLists.txt 
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 5)
    set_property (TARGET t PROPERTY COMPILE_FLAGS " -std=c++0x" APPEND_STRING)
  endif ()
endif ()

With this patch, it compiles correctly with the three tested gcc versions. As it does not change the flags for gcc versions older than 5, it should still compile correctly with quite old gcc versions.

However, two remarks: 
- CMAKE_CXX_COMPILER_VERSION is supported only since cmake 2.8.8. So it will require a rather recent version of cmake.
- the current provided version of boost compiles with gcc 5, but there is a lot of messages on deprecated std::auto_ptr use. Maybe it would be better to use a more recent boost version ? 
I have tried to compile lsl using a lslboost based on boost 1.58. It compiles correctly. But I have not checked that boost.serialization is backwards compatible with 1.55 (as stated in external/readme.txt)

**Comment by chkothe** [comment]
Hi Boris, great detective work! I think that patch would definitely be
better than what we have currently to maintain compatibility with older gcc
toolchains. I know this isn't pretty, but what do you think about checking
the cmake version first, and using that feature only if cmake>=2.8.8 and
assume gcc 4.x otherwise? Is that possible? Then, if someone runs into this
compile issue again, we can recommend to upgrade their cmake as well (and
there's a good chance that they'll have access to the latest version of it
in their fairly bleeding-edge distribution and even if not it should still
be better to upgrade cmake than up/downgrade gcc or hacking around with
compile switches).

Other than that, I wouldn't be too concerned about boost-related warnings
at this point, it's pretty futile to try to silence them all on the various
compilers... what matters most is that LSL runs bug-free. We'll definitely
upgrade the boost version again, but there should be a good reason (e.g.,
when bugs in asio, threads, atomic, lockfree, etc. are uncovered & fixed or
a compiler no longer works). I'm also usually a bit hesitant to upgrade to
a boost version that has just seen a major rollout of new
features/codepaths in a library that we use, because often enough, there
will be some sort of regression that could to blow up in the face of some
end users... I haven't had the time to inspect the current boost release in
that regard.

**Comment by BorisMansencal** [comment]
Ok, I have created pull request #103 in which I check CMake version before checking gcc version.

**Pull request closed without merging**
