### PR TITLE
Line endings (Fixes #129)

### LINKED ISSUE #129: Inconsistent line endings, all files treated as binary
https://github.com/sccn/labstreaminglayer/commit/ca589891eb94c7c691d1bf0ab5485de0238c545b introduced a .gitattributes file which keeps line endings the same for all users.

Most of the line endings are windows-style, so this makes OS X and Linux text editors confused.  Some of the files have been edited on OS X and Linux, and now are confused on Windows as well because they have multiple forms of line endings in them.

Git has capacity to resolve this automatically if configured differently.  I feel line endings should be normalized to be stored in one consistent manner for all platform-independent textfiles.  Most projects choose unix-style line endings for this.  Git can then be configured to convert these to the user's platform's line endings upon checkout via a .gitattributes file that sets text=auto rather than -text.  See https://help.github.com/articles/dealing-with-line-endings/#example .

### PR DESCRIPTION
**Pull request by xloem**
This patch normalizes all line endings in the git repo to be represented using git's default representation (LF), and marks windows and binary files as such so that they will be properly preserved.

In my attempt to do this safely, I reviewed every file extension in the repository.  I found 47 non-windows-specific text file-extensions, and also text files with no file-extension.  I found 6 Windows text file-extensions, and 12 binary file-extensions, and marked these as such in a new .gitattributes file.

I wasn't really sure how to handle Delphi and C# files.  I ended up not marking them as Windows, because C# is used in Linux with Monotone, and Delphi is used on OS X.

These settings should properly preserve the line endings on Windows.  However, I am not on Windows, so I have not actually tested this.

Fixes #129.

### CODE REVIEW

**Comment by dmedine** [comment]
Thanks again, xloem. I thought I had fixed this, but obviously not. I think I just had a pile of kludges on my local repositories that hid the line ending issues from me. Our servers are down at the moment for annual maintenance. Once they are back up, I will test your pr and merge it.

**Comment by dmedine** [comment]
Checked this out very quickly on Windows and Linux. Seems to work correctly, thanks again xloem!

**Comment by xloem** [comment]
I developed a fear that this change would produce a lot of conflicts.  It might have been wiser to commit and merge with only b8bcf74a84f23a24466b4b61ac4b1bf22ab6149c first.  Let me know if this change causes a problem?

**Comment by dmedine** [comment]
It merged fine. I checked out a few random files on both Windows and 
Linux and everything looked proper. I haven't yet tried to build 
anything, though. I will build LSL on all platforms today and report back.

**Comment by xloem** [comment]
I mean, I was worried that existing unmerged changes may not longer merge easily with the patch in place, since all files have been rewritten.  But I tested with the videocapture branch, and it seems it works fine.

**Comment by dmedine** [comment]
Ah. I understand now. Ok, that's good news.

**Comment by dmedine** [comment]
So I'm actually having some trouble with this. I made some changes to 
the lsl xcode project today and then tried to push them from a Windows 
machine and it wanted to change all the LFs to CRLFs. Likewise, I added 
a line to the .gitignore file in Windows, tried to add from Mac, and it 
wanted to change CRLFs to LFs. I think the ideal behavior is that this 
doesn't happen, right? Maybe I am misunderstanding the .gitattributes file.

**Comment by xloem** [comment]
Hmmm I wasn't expecting files to be transferred between Windows and non-Windows machines outside of git.  In that case the xcode files should be stored with LF endings on all platforms.  What are the extensions of the problematic files?

The .gitignore file sounds correct to me.  It should be stored LF in the git repo and on the mac, but checked out with CRLF on Windows so that Windows text editors will process it correctly.  But perhaps I am misunderstanding what you are saying.  Is the incorrect transformation happening in the commit to the repository, or in the checkout to the local drive?  Or could you paste in the problematic git output?

**Comment by xloem** [comment]
Git rewrites the line endings when a commit is made to match the specifications of the .gitattributes file, so that the line endings are consistent throughout the project.  So, platform-independent files will have CRLF changed to LF, unless you are on Windows.  I also added lines such that Windows-specific files will have LF changed to CRLF, always, but this could be disabled.

**Comment by dmedine** [comment]
OK. I would say we are good then so long as people don't mix operating 
systems J

**Pull request merged**
