### PR TITLE
Fix memory leak in pull_chunk when not supplying a destination object

### PR DESCRIPTION
**Pull request by schnoy**
This is a fix for the memory leak in pull_chunk in the python binding when using a string stream. The problem was mentioned in issue #20 but doesn't seem to have been fixed in the python binding yet.

### CODE REVIEW

**Comment by dmedine** [comment]
Thanks for this Schnoy. One question I have is whether or not you are getting memory leaks using the latest version of LSL. xloem plugged some memory leaks in the core library a little while ago ([here](https://github.com/sccn/labstreaminglayer/pull/125)). I wonder if this already fixes the leaking in the Python API? I will investigate this.

**Comment by dmedine** [comment]
So I did a little test and didn't see any memory leaks at all, actually. I used the liblsl-Python example ReceiveDataInChunks with liblsl before and after xloem's fix using both your PR and the current source code. I saw no leaking in any of the 4 scenarios. Can you point me to a situation where you have seen memory leaking out of inlet.pull_chunk()? It could be that my test procedure somehow didn't trigger it. Thanks.

**Comment by schnoy** [comment]
As far as I can see, the ReceiveDataInChunks example uses an eeg-type stream and not Marker type with string data.
If you modify it to read from a Marker stream with input from the SendStringMarkers example, you should be able to reproduce the memory leak.
When reading from a string stream, pull_chunk in the python binding calls lsl_pull_chunk_str with an array of c_char_p pointers to fetch the resulting marker strings for which lsl_pull_chunk_str allocates memory with malloc and stores the addresses in the c_char_p pointers.
The results are then converted to python strings but the memory buffers that were allocated by lsl_pull_chunk_str are never freed by the python binding afterwards.
I did not yet have time to recompile the dll from source and test the fixes you mentioned but looking at xloems commit it seems to me that it does not address this issue.

**Comment by cboulay** [comment]
I just tested PerformanceTest.py which does make use of string streams, and lsl_pull_chunk_str was definitely leaking (tested with Mac OS Instruments). With the changes in this pull request, it was no longer leaking.

**Comment by dmedine** [comment]
Thanks @schnoy for clearing that up. I somehow didn't grasp that this 
had to do with marker streams. Thanks @cboulay for running the test and 
validating the changes. I will merge it in. Great work!

**Pull request merged**
